import type { CommandsFile } from "./commands-schema";
import type { ClientManifest, JsonShape, ManifestEndpoint } from "./manifest-schema";

const GENERATED_HEADER = (manifest: ClientManifest) =>
  `// GENERATED by rkt derive-client. Do not edit.
// site: ${manifest.site}
// manifest schemaVersion: ${manifest.schemaVersion}
// derived from HAR sha256: ${manifest.harSha256}
// recorded: ${manifest.recordedAt}
// Regenerate with: /derive-client, then generate.ts --manifest <path>
`;

const READ_METHODS = new Set(["GET", "HEAD"]);

/**
 * Derive readable subcommand names from paths rather than raw endpoint ids.
 * Collisions are resolved by appending -2, -3 in manifest order, so the same
 * manifest always regenerates the same names.
 */
export function commandNames(endpoints: ManifestEndpoint[]): Map<string, string> {
  const out = new Map<string, string>();
  const used = new Map<string, number>();

  for (const endpoint of endpoints) {
    const method = endpoint.method.toUpperCase();
    if (!READ_METHODS.has(method)) {
      throw new Error(
        `refusing ${endpoint.method} ${endpoint.pathTemplate}: read mode derives GET and HEAD only`,
      );
    }

    const segments = endpoint.pathTemplate
      .split("/")
      .filter(Boolean)
      .filter((s) => !/^\{.*\}$/.test(s))
      .map((s) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, ""))
      .filter(Boolean);

    const parts = method === "GET" ? segments : [method.toLowerCase(), ...segments];
    const base = parts.length > 0 ? parts.join("-") : method.toLowerCase();

    const seen = used.get(base) ?? 0;
    used.set(base, seen + 1);
    out.set(endpoint.id, seen === 0 ? base : `${base}-${seen + 1}`);
  }

  return out;
}

export function typeName(command: string): string {
  const pascal = command
    .split("-")
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
  return `${pascal}Response`;
}

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

function propKey(name: string): string {
  return IDENTIFIER.test(name) ? name : JSON.stringify(name);
}

/** Render a shape as an inline type expression at the given indent depth. */
function typeExpr(shape: JsonShape, depth: number): string {
  const pad = "  ".repeat(depth);
  const padInner = "  ".repeat(depth + 1);

  switch (shape.type) {
    case "object": {
      const keys = Object.keys(shape.properties);
      if (keys.length === 0) return "Record<string, unknown>";
      const lines = keys.map((key) => {
        const optional = shape.required.includes(key) ? "" : "?";
        return `${padInner}${propKey(key)}${optional}: ${typeExpr(shape.properties[key], depth + 1)};`;
      });
      return `{\n${lines.join("\n")}\n${pad}}`;
    }
    case "array":
      return `Array<${typeExpr(shape.items, depth)}>`;
    case "string":
    case "number":
    case "boolean":
    case "null":
      return shape.type;
    default:
      return "unknown";
  }
}

/** Emit one exported type declaration for an endpoint's response shape. */
export function emitType(shape: JsonShape, name: string): string {
  return `export type ${name} = ${typeExpr(shape, 0)};\n`;
}

export function emitTypes(manifest: ClientManifest): string {
  const names = commandNames(manifest.endpoints);
  const blocks = manifest.endpoints.map((endpoint) =>
    emitType(endpoint.responseShape, typeName(names.get(endpoint.id)!)),
  );
  return `${GENERATED_HEADER(manifest)}\n${blocks.join("\n")}`;
}

export function emitCli(manifest: ClientManifest, commands?: CommandsFile): string {
  for (const endpoint of manifest.endpoints) {
    if (!READ_METHODS.has(endpoint.method.toUpperCase())) {
      throw new Error(
        `cannot generate ${endpoint.method} ${endpoint.pathTemplate}: read mode emits GET and HEAD only`,
      );
    }
  }
  const body = commands ? emitTaskCli(manifest, commands) : emitEndpointCli(manifest);
  return `#!/usr/bin/env bun\n${body}`;
}

function emitEndpointCli(manifest: ClientManifest): string {
  const names = commandNames(manifest.endpoints);
  const commands = manifest.endpoints.map((endpoint) => ({
    command: names.get(endpoint.id)!,
    id: endpoint.id,
    method: endpoint.method,
    pathTemplate: endpoint.pathTemplate,
    params: endpoint.params,
  }));

  const responseTypes = manifest.endpoints.map((e) => typeName(names.get(e.id)!));
  const responseMap = manifest.endpoints.map(
    (e) => `  ${JSON.stringify(names.get(e.id)!)}: ${typeName(names.get(e.id)!)};`,
  );

  const typeImport =
    manifest.endpoints.length > 0
      ? `import type { ${responseTypes.join(", ")} } from "./types";\n`
      : "";
  const responseFor =
    manifest.endpoints.length > 0
      ? `/** Response type per command, for callers importing this module. */
export type ResponseFor = {
${responseMap.join("\n")}
};

`
      : "";

  return `${GENERATED_HEADER(manifest)}
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { validateManifest } from "../lib/manifest-schema";
import { createScheduler } from "../lib/scheduler";
import { reauthViaProfile } from "../lib/reauth";
import { refreshViaOidc } from "../lib/refresh";
import { maskHeaders, readSecrets, redactAll, REFRESH_TOKEN_KEY, writeSecret } from "../lib/secrets";
import { runLifecycle } from "../lib/session";
import { buildRequest, issue } from "../lib/transport";
${typeImport}
interface CommandSpec {
  command: string;
  id: string;
  method: string;
  pathTemplate: string;
  params: Array<{
    name: string;
    in: "path" | "query";
    type: "string" | "number";
    required?: boolean;
    example?: string;
  }>;
}

const COMMANDS: CommandSpec[] = ${JSON.stringify(commands, null, 2)};

${responseFor}function usage(exitCode = 1): never {
  console.error("usage: bun cli.ts <command> [--param value ...] [--dry-run]");
  console.error("");
  console.error("session:");
  console.error("  login                        sign in and save the session");
  console.error("  logout                       remove the saved session and secrets");
  console.error("  auth status                  show token TTL and session age");
  console.error("  install [--name <x>]         symlink this CLI onto your PATH");
  console.error("  uninstall                    remove the PATH launcher (keeps the client)");
  console.error("  help                         show this message");
  console.error("");
  console.error("commands:");
  for (const c of COMMANDS) {
    const params = c.params.map((p) => \`--\${p.name} <\${p.type}>\`).join(" ");
    console.error(\`  \${c.command.padEnd(28)} \${c.method} \${c.pathTemplate} \${params}\`);
  }
  process.exit(exitCode);
}

async function main() {
  const handled = await runLifecycle(
    process.argv[2],
    process.argv[3],
    fileURLToPath(new URL("./client.json", import.meta.url)),
  );
  if (handled) return;

  const commandName = process.argv[2];
  if (commandName === "help" || commandName === "--help" || commandName === "-h") usage(0);
  if (!commandName || commandName.startsWith("-")) usage();

  const command = COMMANDS.find((c) => c.command === commandName);
  if (!command) {
    console.error(\`unknown command: \${commandName}\`);
    usage();
  }

  const params: Record<string, string> = {};
  for (const p of command.params) {
    const i = process.argv.indexOf(\`--\${p.name}\`);
    if (i !== -1 && process.argv[i + 1] !== undefined) {
      params[p.name] = process.argv[i + 1];
    }
  }

  const manifest = validateManifest(
    JSON.parse(await readFile(new URL("./client.json", import.meta.url), "utf8")),
  );
  const endpoint = manifest.endpoints.find((e) => e.id === command.id);
  if (!endpoint) {
    console.error(\`endpoint \${command.id} is missing from client.json; regenerate this client\`);
    process.exit(1);
  }

  const secret = await readSecrets(manifest.site);
  if (manifest.auth && !secret) {
    console.error(
      \`no stored credential for "\${manifest.site}". Re-run /derive-client to refresh it.\`,
    );
    process.exit(1);
  }

  if (manifest.auth?.expiry && Date.parse(manifest.auth.expiry) < Date.now()) {
    console.error(
      \`warning: stored credential expired at \${manifest.auth.expiry}; expect a 401.\`,
    );
  }

  let built = buildRequest(manifest, endpoint, params, secret);

  if (process.argv.includes("--dry-run")) {
    // Mask header VALUES before serializing. Redacting the serialized string
    // instead would miss a secret containing a quote, because JSON escaping
    // rewrites it (ab"cd becomes ab\\"cd and no longer matches).
    console.log(
      JSON.stringify(
        { method: built.method, url: built.url, headers: maskHeaders(built.headers, secret) },
        null,
        2,
      ),
    );
    return;
  }

  const scheduler = createScheduler();
  let { status, body } = await issue(built, scheduler);

  // A 401 on a derived client almost always means "stale", not "wrong".
  // Renew and retry once before reporting failure. Tiers run cheapest first:
  // an OIDC refresh is a single POST, while browser re-auth costs a headless
  // Chrome launch but survives a refresh token that has also expired.
  if (status === 401 && secret) {
    let renewedValues: Record<string, string> | null = null;

    if (manifest.refresh?.kind === "oidc" && secret[REFRESH_TOKEN_KEY]) {
      console.error("credential rejected (401); refreshing via OIDC...");
      const renewed = await refreshViaOidc(
        manifest.refresh,
        secret[REFRESH_TOKEN_KEY],
        manifest.userAgent,
      );
      if (renewed) {
        renewedValues = { ...secret };
        const cookieName = manifest.refresh.accessTokenCookie;
        if (cookieName) renewedValues[\`cookie:\${cookieName}\`] = renewed.accessToken;
        const bearer = manifest.authBundle?.credentials.find((c) => c.kind === "bearer");
        if (bearer) renewedValues[bearer.location] = \`Bearer \${renewed.accessToken}\`;
        if (renewed.refreshToken) renewedValues[REFRESH_TOKEN_KEY] = renewed.refreshToken;
      } else {
        console.error("OIDC refresh refused; falling back to browser re-auth...");
      }
    }

    if (!renewedValues) {
      const entryUrl =
        manifest.refresh?.kind === "browser" ? manifest.refresh.entryUrl : \`\${manifest.baseUrl}/\`;
      const wanted = (manifest.authBundle?.credentials ?? []).map((c) => c.location);
      console.error("re-authenticating with the recorded browser profile...");
      let harvested = null;
      try {
        harvested = await reauthViaProfile(manifest.site, entryUrl, wanted);
      } catch (err) {
        // A missing dependency is not an expired session; say which it is.
        console.error((err as Error).message);
      }
      if (harvested) {
        renewedValues = { ...secret, ...harvested.values };
      } else {
        console.error(
          \`could not re-authenticate "\${manifest.site}". The saved browser profile is no \` +
            \`longer signed in; re-run /derive-client to sign in again.\`,
        );
      }
    }

    if (renewedValues) {
      await writeSecret(manifest.site, renewedValues);
      built = buildRequest(manifest, endpoint, params, renewedValues);
      ({ status, body } = await issue(built, scheduler));
    }
  }

  if (status >= 400) {
    console.error(\`HTTP \${status}\`);
    console.error(redactAll(body, secret).slice(0, 2000));
    process.exit(1);
  }
  console.log(redactAll(body, secret));
}

if (import.meta.main) {
  try {
    await main();
  } catch (err) {
    // buildRequest throws on a missing path param; without this the user gets
    // a raw stack trace while every other failure path prints a clean message.
    console.error((err as Error).message);
    process.exit(1);
  }
}
`;
}

function emitTaskCli(manifest: ClientManifest, commands: CommandsFile): string {
  const hasIdentity = !!commands.identity;
  const identityLiteral = hasIdentity ? JSON.stringify(commands.identity) : "undefined";
  const whoamiImport = hasIdentity ? ", runWhoami" : "";
  const whoamiDispatch = hasIdentity
    ? `
  if (name === "whoami") {
    console.log(await runWhoami(SITE, IDENTITY, caller));
    return;
  }
`
    : "";
  return `${GENERATED_HEADER(manifest)}
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { validateManifest } from "../lib/manifest-schema";
import { createScheduler } from "../lib/scheduler";
import { createCaller } from "../lib/runtime";
import { runCommand${whoamiImport} } from "../lib/command-runner";
import type { CommandSpec, IdentitySpec } from "../lib/commands-schema";
import { readSecrets } from "../lib/secrets";
import { runLifecycle } from "../lib/session";

const COMMANDS: CommandSpec[] = ${JSON.stringify(commands.commands, null, 2)};
const IDENTITY: IdentitySpec | undefined = ${identityLiteral};
const SITE = ${JSON.stringify(manifest.site)};

function hasFlag(name: string): boolean {
  return process.argv.includes(\`--\${name}\`);
}
function flagValue(name: string): string | undefined {
  const i = process.argv.indexOf(\`--\${name}\`);
  return i === -1 ? undefined : process.argv[i + 1];
}

function usage(exitCode = 1): never {
  console.error("usage: bun cli.ts <command> [--param value ...] [--json] [--raw] [--limit n]");
  console.error("");
  console.error("session:");
  console.error("  login                    sign in and save the session");
  console.error("  logout                   remove the saved session and secrets");
  console.error("  auth status              show token TTL and session age");
  if (IDENTITY) console.error("  whoami                   show the signed-in user");
  console.error("  install [--name <x>]     symlink this CLI onto your PATH");
  console.error("  uninstall                remove the PATH launcher (keeps the client)");
  console.error("  help                     show this message");
  console.error("");
  console.error("commands:");
  for (const c of COMMANDS) console.error(\`  \${c.name.padEnd(22)} \${c.summary}\`);
  process.exit(exitCode);
}

async function main() {
  const manifestPath = fileURLToPath(new URL("./client.json", import.meta.url));
  if (await runLifecycle(process.argv[2], process.argv[3], manifestPath)) return;

  const name = process.argv[2];
  if (name === "help" || name === "--help" || name === "-h") usage(0);
  if (!name || name.startsWith("-")) usage();

  const manifest = validateManifest(JSON.parse(await readFile(manifestPath, "utf8")));
  const secret = await readSecrets(manifest.site);
  // Same pre-flight the manual and fallback CLIs carry: a clear "run login"
  // beats a confusing 401 when the site needs auth but nothing is stored.
  if (manifest.auth && !secret) {
    console.error(\`no stored credential for "\${manifest.site}". Run: bun cli.ts login\`);
    process.exit(1);
  }
  const scheduler = createScheduler();
  const caller = createCaller(manifest, scheduler, secret);
${whoamiDispatch}
  const cmd = COMMANDS.find((c) => c.name === name);
  if (!cmd) {
    console.error(\`unknown command: \${name}\`);
    usage();
  }

  // Override declared params from --name value; global flags are never treated as params.
  const overrideParams: Record<string, string> = {};
  for (const key of Object.keys(cmd.call.params ?? {})) {
    const v = flagValue(key);
    if (v !== undefined) overrideParams[key] = v;
  }

  const limitRaw = flagValue("limit");
  const limitNum = limitRaw !== undefined ? Number(limitRaw) : NaN;
  const flags = {
    json: hasFlag("json"),
    raw: hasFlag("raw"),
    // Ignore a non-numeric --limit rather than silently slicing to an empty result.
    limit: Number.isFinite(limitNum) ? limitNum : undefined,
  };
  // --json forces JSON output of the primary response (redaction still applies).
  const toRun = flags.json ? { ...cmd, output: { ...cmd.output, kind: "json" as const } } : cmd;

  const out = await runCommand(toRun, {
    manifest,
    site: SITE,
    caller,
    identity: IDENTITY,
    flags,
    now: new Date(),
    overrideParams,
  });
  console.log(out.rendered);
}

if (import.meta.main) {
  main().catch((err) => {
    console.error((err as Error).message);
    process.exit(1);
  });
}
`;
}
