import type { CommandSpec, CommandsFile } from "./commands-schema";
import { shapeTypeAt } from "./commands-schema";
import type { ClientManifest, JsonShape, ManifestEndpoint } from "./manifest-schema";

const GENERATED_HEADER = (manifest: ClientManifest) =>
  `// GENERATED by rkt derive-client. Do not edit.
// site: ${manifest.site}
// manifest schemaVersion: ${manifest.schemaVersion}
// derived from HAR sha256: ${manifest.harSha256}
// recorded: ${manifest.recordedAt}
// Regenerate with: /derive-client, then generate.ts --manifest <path>
`;

const READ_METHODS = new Set(["GET", "HEAD"]);

/**
 * Derive readable subcommand names from paths rather than raw endpoint ids.
 * Collisions are resolved by appending -2, -3 in manifest order, so the same
 * manifest always regenerates the same names.
 */
export function commandNames(
  endpoints: ManifestEndpoint[],
  opts: { allowWrites?: boolean } = {},
): Map<string, string> {
  const out = new Map<string, string>();
  const used = new Map<string, number>();

  for (const endpoint of endpoints) {
    const method = endpoint.method.toUpperCase();
    if (!READ_METHODS.has(method) && !opts.allowWrites) {
      throw new Error(
        `refusing ${endpoint.method} ${endpoint.pathTemplate}: read mode derives GET and HEAD only`,
      );
    }

    const segments = endpoint.pathTemplate
      .split("/")
      .filter(Boolean)
      .filter((s) => !/^\{.*\}$/.test(s))
      .map((s) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, ""))
      .filter(Boolean);

    const parts = method === "GET" ? segments : [method.toLowerCase(), ...segments];
    const base = parts.length > 0 ? parts.join("-") : method.toLowerCase();

    const seen = used.get(base) ?? 0;
    used.set(base, seen + 1);
    out.set(endpoint.id, seen === 0 ? base : `${base}-${seen + 1}`);
  }

  return out;
}

export function typeName(command: string): string {
  const pascal = command
    .split("-")
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
  return `${pascal}Response`;
}

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

function propKey(name: string): string {
  return IDENTIFIER.test(name) ? name : JSON.stringify(name);
}

/** Render a shape as an inline type expression at the given indent depth. */
function typeExpr(shape: JsonShape, depth: number): string {
  const pad = "  ".repeat(depth);
  const padInner = "  ".repeat(depth + 1);

  switch (shape.type) {
    case "object": {
      const keys = Object.keys(shape.properties);
      if (keys.length === 0) return "Record<string, unknown>";
      const lines = keys.map((key) => {
        const optional = shape.required.includes(key) ? "" : "?";
        return `${padInner}${propKey(key)}${optional}: ${typeExpr(shape.properties[key], depth + 1)};`;
      });
      return `{\n${lines.join("\n")}\n${pad}}`;
    }
    case "array":
      return `Array<${typeExpr(shape.items, depth)}>`;
    case "string":
    case "number":
    case "boolean":
    case "null":
      return shape.type;
    default:
      return "unknown";
  }
}

/** Emit one exported type declaration for an endpoint's response shape. */
export function emitType(shape: JsonShape, name: string): string {
  return `export type ${name} = ${typeExpr(shape, 0)};\n`;
}

export function emitTypes(manifest: ClientManifest): string {
  const names = commandNames(manifest.endpoints, { allowWrites: manifest.mode === "full" });
  const blocks = manifest.endpoints.map((endpoint) =>
    emitType(endpoint.responseShape, typeName(names.get(endpoint.id)!)),
  );
  return `${GENERATED_HEADER(manifest)}\n${blocks.join("\n")}`;
}

export function emitCli(manifest: ClientManifest, commands?: CommandsFile): string {
  if (manifest.mode !== "full") {
    for (const endpoint of manifest.endpoints) {
      if (!READ_METHODS.has(endpoint.method.toUpperCase())) {
        throw new Error(
          `cannot generate ${endpoint.method} ${endpoint.pathTemplate}: read mode emits GET and HEAD only`,
        );
      }
    }
  }
  const body = commands ? emitTaskCli(manifest, commands) : emitEndpointCli(manifest);
  return `#!/usr/bin/env bun\n${body}`;
}

function emitEndpointCli(manifest: ClientManifest): string {
  // The fallback CLI is uncurated. A write must never appear here; writes
  // require an authored commands.json task.
  //
  // Name from the FULL endpoint list -- the same list emitTypes names from --
  // then filter to reads. Naming only the read subset would let a write
  // endpoint's collision-driven "-2" suffix diverge between the command name
  // here and the type name in types.ts (same base, different endpoint order
  // once writes are excluded), which silently mislabels a ResponseFor entry.
  const names = commandNames(manifest.endpoints, { allowWrites: manifest.mode === "full" });
  const readEndpoints = manifest.endpoints.filter((e) => READ_METHODS.has(e.method.toUpperCase()));
  const commands = readEndpoints.map((endpoint) => ({
    command: names.get(endpoint.id)!,
    id: endpoint.id,
    method: endpoint.method,
    pathTemplate: endpoint.pathTemplate,
    params: endpoint.params,
  }));

  const responseTypes = readEndpoints.map((e) => typeName(names.get(e.id)!));
  const responseMap = readEndpoints.map(
    (e) => `  ${JSON.stringify(names.get(e.id)!)}: ${typeName(names.get(e.id)!)};`,
  );

  const typeImport =
    readEndpoints.length > 0
      ? `import type { ${responseTypes.join(", ")} } from "./types";\n`
      : "";
  const responseFor =
    readEndpoints.length > 0
      ? `/** Response type per command, for callers importing this module. */
export type ResponseFor = {
${responseMap.join("\n")}
};

`
      : "";

  return `${GENERATED_HEADER(manifest)}
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { validateManifest } from "../lib/manifest-schema";
import { createScheduler } from "../lib/scheduler";
import { reauthViaProfile } from "../lib/reauth";
import { refreshViaOidc } from "../lib/refresh";
import { capText, CliError, footer, writeSpill } from "../lib/overflow";
import { maskHeaders, readSecrets, redactAll, REFRESH_TOKEN_KEY, writeSecret } from "../lib/secrets";
import { runLifecycle } from "../lib/session";
import { buildRequest, issue } from "../lib/transport";
${typeImport}
interface CommandSpec {
  command: string;
  id: string;
  method: string;
  pathTemplate: string;
  params: Array<{
    name: string;
    in: "path" | "query";
    type: "string" | "number";
    required?: boolean;
    example?: string;
  }>;
}

const COMMANDS: CommandSpec[] = ${JSON.stringify(commands, null, 2)};

${responseFor}const STARTED_AT = Date.now();

function fail(message: string, hint: string, exitCode = 1): never {
  console.error(message);
  console.error(\`hint: \${hint}\`);
  console.error(footer({ exitCode, startedAt: STARTED_AT, size: { bytes: 0 } }));
  process.exit(exitCode);
}

/** Nearest command name: prefix match first, then smallest edit distance. */
function suggest(name: string, names: string[]): string | undefined {
  const pre = names.find((n) => n.startsWith(name) || name.startsWith(n));
  if (pre) return pre;
  let best: string | undefined, bestD = 4;
  for (const n of names) {
    const d = editDistance(name, n);
    if (d < bestD) { bestD = d; best = n; }
  }
  return best;
}
function editDistance(a: string, b: string): number {
  const dp = Array.from({ length: a.length + 1 }, (_, i) => [i, ...Array(b.length).fill(0)]);
  for (let j = 0; j <= b.length; j++) dp[0][j] = j;
  for (let i = 1; i <= a.length; i++)
    for (let j = 1; j <= b.length; j++)
      dp[i][j] = Math.min(dp[i - 1][j] + 1, dp[i][j - 1] + 1, dp[i - 1][j - 1] + (a[i - 1] === b[j - 1] ? 0 : 1));
  return dp[a.length][b.length];
}

function endpointHelp(c: CommandSpec): string {
  const lines: string[] = [];
  lines.push(\`\${c.command} — \${c.method} \${c.pathTemplate}\`);
  if (c.params.length) {
    lines.push("params:");
    for (const p of c.params) {
      lines.push(\`  --\${p.name} <\${p.type}>\${p.in === "path" ? " (required, path)" : " (query)"}\`);
    }
  } else {
    lines.push("params: none");
  }
  const example = c.params.map((p) => \`--\${p.name} <value>\`).join(" ");
  lines.push(\`example: bun cli.ts \${c.command}\${example ? " " + example : ""} --dry-run\`);
  return lines.join("\\n");
}

function usage(exitCode = 1): never {
  console.error("usage: bun cli.ts <command> [--param value ...] [--dry-run]");
  console.error("");
  console.error("session:");
  console.error("  login                        sign in and save the session");
  console.error("  logout                       remove the saved session and secrets");
  console.error("  auth status                  show token TTL and session age");
  console.error("  install [--name <x>]         symlink this CLI onto your PATH");
  console.error("  uninstall                    remove the PATH launcher (keeps the client)");
  console.error("  help                         show this message");
  console.error("");
  console.error("commands:");
  for (const c of COMMANDS) {
    const params = c.params.map((p) => \`--\${p.name} <\${p.type}>\`).join(" ");
    console.error(\`  \${c.command.padEnd(28)} \${c.method} \${c.pathTemplate} \${params}\`);
  }
  console.error("");
  console.error("run: bun cli.ts <command> --help for params and an example");
  process.exit(exitCode);
}

async function main() {
  const handled = await runLifecycle(
    process.argv[2],
    process.argv[3],
    fileURLToPath(new URL("./client.json", import.meta.url)),
  );
  if (handled) return;

  const commandName = process.argv[2];
  if (commandName === "help" || commandName === "--help" || commandName === "-h") usage(0);
  if (!commandName || commandName.startsWith("-")) usage();

  const command = COMMANDS.find((c) => c.command === commandName);
  if (!command) {
    const near = suggest(commandName, COMMANDS.map((c) => c.command));
    fail(
      \`unknown command: \${commandName}\${near ? \`. did you mean \${near}?\` : ""}\`,
      "run: bun cli.ts help for the command list",
      2,
    );
  }

  if (process.argv.includes("--help")) {
    console.log(endpointHelp(command));
    return;
  }

  const params: Record<string, string> = {};
  for (const p of command.params) {
    const i = process.argv.indexOf(\`--\${p.name}\`);
    if (i !== -1 && process.argv[i + 1] !== undefined) {
      params[p.name] = process.argv[i + 1];
    }
  }

  for (const p of command.params) {
    if (p.in === "path" && params[p.name] === undefined) {
      console.error(endpointHelp(command));
      fail(\`missing required param: --\${p.name}\`, \`see usage above\`, 2);
    }
  }

  const manifest = validateManifest(
    JSON.parse(await readFile(new URL("./client.json", import.meta.url), "utf8")),
  );
  const endpoint = manifest.endpoints.find((e) => e.id === command.id);
  if (!endpoint) {
    fail(
      \`endpoint \${command.id} is missing from client.json\`,
      "regenerate this client: bash regenerate.sh",
      1,
    );
  }

  const secret = await readSecrets(manifest.site);
  if (manifest.auth && !secret) {
    fail(
      \`no stored credential for "\${manifest.site}"\`,
      "re-run /derive-client to refresh it",
      4,
    );
  }

  if (manifest.auth?.expiry && Date.parse(manifest.auth.expiry) < Date.now()) {
    console.error(
      \`warning: stored credential expired at \${manifest.auth.expiry}; expect a 401.\`,
    );
  }

  let built = buildRequest(manifest, endpoint, params, secret);

  if (process.argv.includes("--dry-run")) {
    // Mask header VALUES before serializing. Redacting the serialized string
    // instead would miss a secret containing a quote, because JSON escaping
    // rewrites it (ab"cd becomes ab\\"cd and no longer matches).
    console.log(
      JSON.stringify(
        { method: built.method, url: built.url, headers: maskHeaders(built.headers, secret) },
        null,
        2,
      ),
    );
    return;
  }

  const scheduler = createScheduler();
  let { status, body } = await issue(built, scheduler);

  // A 401 on a derived client almost always means "stale", not "wrong".
  // Renew and retry once before reporting failure. Tiers run cheapest first:
  // an OIDC refresh is a single POST, while browser re-auth costs a headless
  // Chrome launch but survives a refresh token that has also expired.
  if (status === 401 && secret) {
    let renewedValues: Record<string, string> | null = null;

    if (manifest.refresh?.kind === "oidc" && secret[REFRESH_TOKEN_KEY]) {
      console.error("credential rejected (401); refreshing via OIDC...");
      const renewed = await refreshViaOidc(
        manifest.refresh,
        secret[REFRESH_TOKEN_KEY],
        manifest.userAgent,
      );
      if (renewed) {
        renewedValues = { ...secret };
        const cookieName = manifest.refresh.accessTokenCookie;
        if (cookieName) renewedValues[\`cookie:\${cookieName}\`] = renewed.accessToken;
        const bearer = manifest.authBundle?.credentials.find((c) => c.kind === "bearer");
        if (bearer) renewedValues[bearer.location] = \`Bearer \${renewed.accessToken}\`;
        if (renewed.refreshToken) renewedValues[REFRESH_TOKEN_KEY] = renewed.refreshToken;
      } else {
        console.error("OIDC refresh refused; falling back to browser re-auth...");
      }
    }

    if (!renewedValues) {
      const entryUrl =
        manifest.refresh?.kind === "browser" ? manifest.refresh.entryUrl : \`\${manifest.baseUrl}/\`;
      const wanted = (manifest.authBundle?.credentials ?? []).map((c) => c.location);
      console.error("re-authenticating with the recorded browser profile...");
      let harvested = null;
      try {
        harvested = await reauthViaProfile(manifest.site, entryUrl, wanted);
      } catch (err) {
        // A missing dependency is not an expired session; say which it is.
        console.error((err as Error).message);
      }
      if (harvested) {
        renewedValues = { ...secret, ...harvested.values };
      } else {
        fail(
          \`could not re-authenticate "\${manifest.site}". The saved browser profile is no \` +
            \`longer signed in; re-run /derive-client to sign in again.\`,
          "re-run /derive-client to sign in again",
          4,
        );
      }
    }

    if (renewedValues) {
      await writeSecret(manifest.site, renewedValues);
      built = buildRequest(manifest, endpoint, params, renewedValues);
      ({ status, body } = await issue(built, scheduler));
    }
  }

  if (status >= 400) {
    const redacted = redactAll(body, secret);
    const spill = await writeSpill(manifest.site, command.command, redacted, new Date()).catch(() => undefined);
    fail(
      \`HTTP \${status}\\n\${redacted.slice(0, 2000)}\`,
      status === 403
        ? \`the session may lack permission for this resource; if the whole client fails, try: bun cli.ts login\${spill ? \`. full body: \${spill}\` : ""}\`
        : \`\${spill ? \`full body: \${spill}. \` : ""}re-run with --dry-run to inspect the request\`,
      status === 401 ? 4 : 1,
    );
  }
  const redacted = redactAll(body, secret);
  const cap = capText(redacted);
  let spillPath: string | undefined;
  if (cap.capped) {
    spillPath = await writeSpill(manifest.site, command.command, redacted, new Date());
    console.error(\`hint: output capped at 50KB; full body: \${spillPath}\`);
  }
  process.stdout.write(cap.text);
  console.error(footer({ exitCode: 0, startedAt: STARTED_AT, size: { bytes: Buffer.byteLength(redacted) }, spillPath }));
}

if (import.meta.main) {
  try {
    await main();
  } catch (err) {
    if (err instanceof CliError) fail(err.message, err.hint, err.exitCode);
    fail((err as Error).message, "re-run with --dry-run to inspect the request", 1);
  }
}
`;
}

function argFlags(
  cmd: Pick<CommandSpec, "call">,
  manifest: ClientManifest,
): { name: string; type?: string; hint?: string }[] {
  const ep = manifest.endpoints.find((e) => e.id === cmd.call.endpoint);
  const shape = ep?.writeSemantics?.bodyShape ?? null;
  const hints = ep?.writeSemantics?.bodyHints ?? {};
  const out: { name: string; type?: string; hint?: string }[] = [];
  const seen = new Set<string>();

  const walk = (node: unknown, path: string) => {
    if (typeof node === "string" && node.startsWith("@arg:")) {
      // The same @arg: name can be reused at two body paths. One --flag
      // should print once in --help, not once per occurrence.
      const name = node.slice(5);
      if (seen.has(name)) return;
      seen.add(name);
      out.push({
        name,
        type: shapeTypeAt(shape, path),
        hint: hints[path],
      });
      return;
    }
    if (Array.isArray(node)) {
      node.forEach((item, i) => {
        const p = path ? `${path}.${i}` : String(i);
        walk(item, p);
      });
      return;
    }
    if (node && typeof node === "object") {
      for (const [k, v] of Object.entries(node as Record<string, unknown>)) {
        walk(v, path ? `${path}.${k}` : k);
      }
    }
  };
  walk(cmd.call.body, "");
  return out;
}

function emitArgHelp(commands: CommandsFile, manifest: ClientManifest): string {
  const byCmd = Object.fromEntries(
    commands.commands.map((c) => [
      c.name,
      argFlags(c, manifest).map(
        ({ name, type, hint }) => `  --${name} <${hint ?? type ?? "string"}>`,
      ),
    ]),
  );
  return JSON.stringify(byCmd);
}

function emitTaskCli(manifest: ClientManifest, commands: CommandsFile): string {
  const hasIdentity = !!commands.identity;
  const identityLiteral = hasIdentity ? JSON.stringify(commands.identity) : "undefined";
  const whoamiImport = hasIdentity ? ", runWhoami" : "";
  const whoamiDispatch = hasIdentity
    ? `
  if (name === "whoami") {
    console.log(await runWhoami(SITE, IDENTITY, caller));
    return;
  }
`
    : "";
  return `${GENERATED_HEADER(manifest)}
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { validateManifest } from "../lib/manifest-schema";
import { createScheduler } from "../lib/scheduler";
import { createCaller } from "../lib/runtime";
import { finishRun, runCommand${whoamiImport} } from "../lib/command-runner";
import { CliError, footer } from "../lib/overflow";
import type { CommandSpec, IdentitySpec } from "../lib/commands-schema";
import { readSecrets } from "../lib/secrets";
import { runLifecycle } from "../lib/session";
import { writesEnabled } from "../lib/transport";

const COMMANDS: CommandSpec[] = ${JSON.stringify(commands.commands, null, 2)};
const IDENTITY: IdentitySpec | undefined = ${identityLiteral};
const SITE = ${JSON.stringify(manifest.site)};
const ARG_HELP: Record<string, string[]> = ${emitArgHelp(commands, manifest)};
const STARTED_AT = Date.now();

const WRITES_ENABLED = writesEnabled();
// With writes disabled the write commands are not registered at all: they do
// not appear in help and dispatch treats them as unknown.
const VISIBLE: CommandSpec[] = COMMANDS.filter((c) => WRITES_ENABLED || !c.write);
const HAS_HIDDEN_WRITES = COMMANDS.some((c) => c.write) && !WRITES_ENABLED;

function argNames(cmd: CommandSpec): string[] {
  const found = new Set<string>();
  const walk = (node: unknown) => {
    if (typeof node === "string") {
      if (node.startsWith("@arg:")) found.add(node.slice(5));
      return;
    }
    if (node && typeof node === "object") Object.values(node as Record<string, unknown>).forEach(walk);
  };
  walk(cmd.call.body);
  Object.values(cmd.call.params ?? {}).forEach(walk);
  return [...found];
}

function hasFlag(name: string): boolean {
  return process.argv.includes(\`--\${name}\`);
}
function flagValue(name: string): string | undefined {
  const i = process.argv.indexOf(\`--\${name}\`);
  if (i === -1) return undefined;
  const next = process.argv[i + 1];
  // A bare \`--flag\` with no value must not swallow the next flag (e.g. --commit).
  if (next === undefined || next.startsWith("--")) return undefined;
  return next;
}

function fail(message: string, hint: string, exitCode = 1): never {
  console.error(message);
  console.error(\`hint: \${hint}\`);
  console.error(footer({ exitCode, startedAt: STARTED_AT, size: { bytes: 0 } }));
  process.exit(exitCode);
}

/** Nearest command name: prefix match first, then smallest edit distance. */
function suggest(name: string, names: string[]): string | undefined {
  const pre = names.find((n) => n.startsWith(name) || name.startsWith(n));
  if (pre) return pre;
  let best: string | undefined, bestD = 4;
  for (const n of names) {
    const d = editDistance(name, n);
    if (d < bestD) { bestD = d; best = n; }
  }
  return best;
}
function editDistance(a: string, b: string): number {
  const dp = Array.from({ length: a.length + 1 }, (_, i) => [i, ...Array(b.length).fill(0)]);
  for (let j = 0; j <= b.length; j++) dp[0][j] = j;
  for (let i = 1; i <= a.length; i++)
    for (let j = 1; j <= b.length; j++)
      dp[i][j] = Math.min(dp[i - 1][j] + 1, dp[i][j - 1] + 1, dp[i - 1][j - 1] + (a[i - 1] === b[j - 1] ? 0 : 1));
  return dp[a.length][b.length];
}

function commandHelp(cmd: (typeof COMMANDS)[number]): string {
  const lines: string[] = [];
  lines.push(\`\${cmd.name} — \${cmd.summary}\`);
  const params = Object.entries(cmd.call.params ?? {});
  if (params.length) {
    lines.push("params (override with --<name> <value>):");
    for (const [k, v] of params) lines.push(\`  --\${k}   (default: \${v})\`);
    lines.push("  token values: @me, @today, @today±<n><d|w|m|y>; literal @ as @@");
  } else {
    lines.push("params: none declared (nothing is overridable)");
  }
  // Write holes: one flag per @arg: leaf in the body template.
  for (const line of ARG_HELP[cmd.name] ?? []) lines.push(line);
  if (cmd.output.kind === "table" && cmd.output.columns?.length) {
    lines.push(\`columns: \${cmd.output.columns.join(", ")}\`);
  }
  lines.push("global flags: --json --raw --limit <n> --full");
  if (cmd.write) lines.push("write flags:  --commit (send it; without this the write only previews)");
  if (HAS_HIDDEN_WRITES) {
    lines.push("");
    lines.push("write commands are hidden; set RKT_ALLOW_WRITES=1 to enable them");
  }
  const example = params.length
    ? \`\${cmd.name} \${params.map(([k]) => \`--\${k} <value>\`).join(" ")}\`
    : cmd.name;
  lines.push(\`example: bun cli.ts \${example}\`);
  return lines.join("\\n");
}

function usage(exitCode = 1): never {
  console.error("usage: bun cli.ts <command> [--param value ...] [--json] [--raw] [--limit n]");
  console.error("");
  console.error("session:");
  console.error("  login                    sign in and save the session");
  console.error("  logout                   remove the saved session and secrets");
  console.error("  auth status              show token TTL and session age");
  if (IDENTITY) console.error("  whoami                   show the signed-in user");
  console.error("  install [--name <x>]     symlink this CLI onto your PATH");
  console.error("  uninstall                remove the PATH launcher (keeps the client)");
  console.error("  help                     show this message");
  console.error("");
  console.error("commands:");
  for (const c of VISIBLE) console.error(\`  \${c.name.padEnd(22)} \${c.summary}\`);
  if (HAS_HIDDEN_WRITES) {
    console.error("");
    console.error("write commands are hidden; set RKT_ALLOW_WRITES=1 to enable them");
  }
  console.error("");
  console.error("run: bun cli.ts <command> --help for params and an example");
  process.exit(exitCode);
}

async function main() {
  const manifestPath = fileURLToPath(new URL("./client.json", import.meta.url));
  if (await runLifecycle(process.argv[2], process.argv[3], manifestPath)) return;

  const name = process.argv[2];
  if (name === "help" || name === "--help" || name === "-h") usage(0);
  if (!name || name.startsWith("-")) usage();

  const cmd = VISIBLE.find((c) => c.name === name);
  if (name !== "whoami" && !cmd) {
    const near = suggest(name, VISIBLE.map((c) => c.name));
    fail(
      \`unknown command: \${name}\${near ? \`. did you mean \${near}?\` : ""}\`,
      "run: bun cli.ts help for the command list",
      2,
    );
  }
  if (cmd && hasFlag("help")) {
    console.log(commandHelp(cmd));
    return;
  }

  const manifest = validateManifest(JSON.parse(await readFile(manifestPath, "utf8")));
  const secret = await readSecrets(manifest.site);
  // Same pre-flight the manual and fallback CLIs carry: a clear "run login"
  // beats a confusing 401 when the site needs auth but nothing is stored.
  if (manifest.auth && !secret) {
    fail(\`no stored credential for "\${manifest.site}"\`, "run: bun cli.ts login", 4);
  }
  const scheduler = createScheduler();
  const caller = createCaller(manifest, scheduler, secret);
${whoamiDispatch}

  // Override declared params from --name value; global flags are never treated as params.
  const overrideParams: Record<string, string> = {};
  for (const key of Object.keys(cmd.call.params ?? {})) {
    const v = flagValue(key);
    if (v !== undefined) overrideParams[key] = v;
  }

  // Collect --<name> values for every @arg: hole in this command's body.
  const args: Record<string, string> = {};
  for (const name of argNames(cmd)) {
    const v = flagValue(name);
    if (v !== undefined) args[name] = v;
  }

  const limitRaw = flagValue("limit");
  const limitNum = limitRaw !== undefined ? Number(limitRaw) : NaN;
  const flags = {
    json: hasFlag("json"),
    raw: hasFlag("raw"),
    // Ignore a non-numeric --limit rather than silently slicing to an empty result.
    limit: Number.isFinite(limitNum) ? limitNum : undefined,
  };
  // --json forces JSON output of the primary response (redaction still applies).
  const toRun = flags.json ? { ...cmd, output: { ...cmd.output, kind: "json" as const } } : cmd;

  const result = await runCommand(toRun, {
    manifest,
    site: SITE,
    caller,
    identity: IDENTITY,
    flags,
    now: new Date(),
    overrideParams,
    commit: hasFlag("commit"),
    args,
  });
  if (result.kind === "preview") {
    process.stdout.write(result.rendered + "\\n");
    console.error("preview only. Nothing was sent. Re-run with --commit to apply.");
    return;
  }
  const done = await finishRun(SITE, cmd.name, result, { full: hasFlag("full"), now: new Date() });
  process.stdout.write(done.stdout);
  if (done.hint) console.error(\`hint: \${done.hint}\`);
  console.error(footer({ exitCode: 0, startedAt: STARTED_AT, size: done.size, spillPath: done.spillPath }));
}

if (import.meta.main) {
  main().catch((err) => {
    if (err instanceof CliError) fail(err.message, err.hint, err.exitCode);
    fail((err as Error).message, "for writes, omit --commit to preview; otherwise check --help", 1);
  });
}
`;
}
